### ISSUE TITLE
koan can't get port for profile

### ISSUE THREAD

**Issue by wanghaiqing2015** [cobbler/koan#28]
cobbler server change port to 10080,use below command fail to get URL for profile.Should add http_port to URL path.

command:
koan --server=192.168.10.112 --port 10080 --virt --virt-name=main5   --virt-bridge=br0  --profile=centos7.4-x86_64

error message:
```
[root@www ~]# koan --server=192.168.10.112 --port 10080 --virt --virt-name=main5   --virt-bridge=br0  --profile=centos7.4-x86_64
- looking for Cobbler at http://192.168.10.112:10080/cobbler_api
- reading URL: http://192.168.10.112/cblr/svc/op/ks/profile/centos7.4-x86_64
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/koan/utils.py", line 125, in urlread
    fd = urllib2.urlopen(url)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1244, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 111] Connection refused>
- ['/usr/bin/virt-install', '--version']
- ['virt-install', '--version']
- ['virt-install', '--os-variant', 'list']
- ['osinfo-query', '-f', 'short-id', 'os']
Cannot find install source in kickstart file, aborting.
```

**Comment by wanghaiqing2015** [comment]
Anyone?
