### ISSUE TITLE
Problem reporting error with virt-install

### ISSUE THREAD

**Issue by opoplawski** [cobbler/koan#64]
virt-install was failing because of an undefined bridge interface, but koan produces a traceback trying to report the error:
```bash
<class 'ValueError'>
unsupported format character '[' (0x5b) at index 155
  File "/usr/lib/python3.6/site-packages/koan/app.py", line 372, in main
    k.run()
  File "/usr/lib/python3.6/site-packages/koan/app.py", line 526, in run
    self.virt()
  File "/usr/lib/python3.6/site-packages/koan/app.py", line 922, in virt
    return self.net_install(after_download)
  File "/usr/lib/python3.6/site-packages/koan/app.py", line 787, in net_install
    after_download(self, profile_data)
  File "/usr/lib/python3.6/site-packages/koan/app.py", line 920, in after_download
    self.virt_net_install(profile_data)
  File "/usr/lib/python3.6/site-packages/koan/app.py", line 1621, in virt_net_install
    osimport=self.virtinstall_osimport,
  File "/usr/lib/python3.6/site-packages/koan/qcreate.py", line 35, in start_install
    raise utils.InfoException("command failed (%s): %s %s" % (rc, result, result_stderr))
  File "/usr/lib/python3.6/site-packages/koan/cexceptions.py", line 50, in __init__
    self.value = value % args
```
I get the feeling that InfoException was meant to be called like:
```python
  raise utils.InfoException("command failed (%s): %s %s" , (rc, result, result_stderr))
```
but that doesn't look like that is how it is called anywhere.  Time to just drop the whole args option?

Also, none of KoanException, KX, or FileNotFoundException seem to be used as near as I can tell.

**Comment by SchoolGuy** [comment]
From my interactive Python terminal (very bad copy & paste I know):

```
from koan.cexceptions import InfoException
rc = 0
result = "Test"
result_stderr = "Test"
raise InfoException("command failed (%s): %s %s" % (rc, result, result_stderr))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
koan.cexceptions.InfoException: 'command failed (0): Test Test'
raise InfoException("command failed (%s): %s %s", (rc, result, result_stderr))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: __init__() takes 2 positional arguments but 3 were given
```

The real error is that `utils.InfoException` is called instead of just `InfoException`. I will open a PR for it.
